Bilet9/Models/Chef.cs
using Bilet9.Models.Common;

namespace Bilet9.Models;

public class Chef:BaseEntity
{
    public string Name { get; set; } = string.Empty;
    public string ImagePath { get; set; } = string.Empty;
    public int PositionId { get; set; }
    public Position Position { get; set; }
}

Bilet9/Areas/Admin/Controllers/ChefController.cs
using System.Threading.Tasks;
using Bilet9.Context;
using Bilet9.Helper;
using Bilet9.Models;
using Bilet9.ViewModels.ChefViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bilet9.Areas.Admin.Controllers;
[Area("Admin")]
public class ChefController : Controller
{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _environment;
    private readonly string _folderPath;

    public ChefController(AppDbContext context, IWebHostEnvironment environment)
    {
        _context = context;
        _environment = environment;
        _folderPath = Path.Combine(_environment.WebRootPath,"images");
    }

    public async Task<IActionResult> Index()
    {
        var chefs = await _context.Chefs.Select(chef => new ChefGetVM() 
        {
            Id=chef.Id,
            Name=chef.Name,
            ImagePath=chef.ImagePath,
            PositionTitle=chef.Position.Title
        }).ToListAsync();

        return View(chefs);
    }

    public async Task<IActionResult> Create()
    {
        await SendPositionWithViewBag();
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(ChefCreateVM vm)
    {
        await SendPositionWithViewBag();
        if (!ModelState.IsValid)
        {
            return View(vm);
        }
        //Check position
        var isPositionExist = await _context.Positions.AnyAsync(x => x.Id == vm.PositionId);
        if (!isPositionExist)
        {
            return NotFound();
        }

        //Check image size
        if (!vm.Image.CheckSize(2))
        {
            ModelState.AddModelError("Image", "Image size  must be less than 2 mb");
            return View(vm);
        }
        //Check file type
        if (!vm.Image.CheckType("image"))
        {
            ModelState.AddModelError("Image", "File must be image type");
            return View(vm);
        }

        //Create image

        string uniqueFileName = await vm.Image.FileUploadToAsync(_folderPath);

        //Create chef
        Chef chef = new()
        {
            Name=vm.Name,
            PositionId=vm.PositionId,
            ImagePath=uniqueFileName
        };
        await _context.Chefs.AddAsync(chef);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Update(int id)
    {
        await SendPositionWithViewBag();
        var chef = await _context.Chefs.FindAsync(id);
        if (chef is null)
            return NotFound();

        ChefUpdateVM vm = new() 
        { 
            Id=chef.Id,
            Name=chef.Name,
            PositionId=chef.PositionId,
            
        };

        return View(vm);
    }

    [HttpPost]
    public async Task<IActionResult> Update(ChefUpdateVM vm)
    {
        await SendPositionWithViewBag();
        if (!ModelState.IsValid)
        {
            return View(vm);
        }

        //Find chef for update
        var isExistChef=await _context.Chefs.FindAsync(vm.Id);
        if(isExistChef is null)
            return NotFound();

        //Check position
        var isPositionExist = await _context.Positions.AnyAsync(x => x.Id == vm.PositionId);
        if (!isPositionExist)
        {
            return NotFound();
        }

        //Check image size
        if (!vm.Image?.CheckSize(2) ?? false)
        {
            ModelState.AddModelError("Image", "Image size  must be less than 2 mb");
            return View(vm);
        }
        //Check file type
        if (!vm.Image?.CheckType("image") ?? false)
        {
            ModelState.AddModelError("Image", "File must be image type");
            return View(vm);
        }
        //Update
        isExistChef.Name = vm.Name;
        isExistChef.PositionId = vm.PositionId;

        if(vm.Image is { })
        {
            string newImagePath = await vm.Image.FileUploadToAsync(_folderPath);
            string deletePath = Path.Combine(_folderPath, isExistChef.ImagePath);
            FileHelper.DeleteFile(deletePath);
            isExistChef.ImagePath = newImagePath; 
        }
        _context.Chefs.Update(isExistChef);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(int id)
    {
        var chef = await _context.Chefs.FindAsync(id);
        if(chef is null)
            return NotFound();
        _context.Chefs.Remove(chef);
        await _context.SaveChangesAsync();

        //Delete image

        string deletedPath = Path.Combine(_folderPath, chef.ImagePath);
        FileHelper.DeleteFile(deletedPath);

        return RedirectToAction("Index");
    }
    private async Task SendPositionWithViewBag()
    {
        var position = await _context.Positions.ToListAsync();
        ViewBag.Positions = position;
    }
}

Bilet9/Areas/Admin/Views/Chef/Create.cshtml
@using Bilet9.Models
@model ChefCreateVM
<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-action="Name" class="form-control" placeholder="Enter Name">
       <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-action="Image" class="form-control" placeholder="Enter Image">
        <span asp-validation-for="Image"></span>
    </div>
    <div class="form-check">
        <select  asp-for="PositionId" class="form-control">
            @foreach(Position position in ViewBag.Positions)
            {
                <option value="@position.Id">@position.Title</option>
            }
        </select>
        <span asp-validation-for="PositionId"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Bilet9/Areas/Admin/Views/Chef/Index.cshtml
@model List<ChefGetVM>
<div class="container">
	<div class="row">

        <div class="row">
            <a asp-action="Create" class="btn btn-success">Create</a>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col"> Id</th>
                    <th scope="col"> Name</th>
                    <th scope="col"> Image</th>
                    <th scope="col"> PositionName</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var chefs in Model)
                {
                    <tr>
                        <th scope="row">@chefs.Id</th>
                        <td>@chefs.Name</td>
                        <td> <img src="~/images/@chefs.ImagePath" alt="Alternate Text" /></td>
                        <td>@chefs.PositionTitle</td>
                        <td>
                            <a asp-action="Update" asp-controller="Chef" asp-route-id="@chefs.Id" class="btn btn-warning">Update</a>
                            <a asp-action="Delete" asp-controller="Chef" asp-route-id="@chefs.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                   
                }

            </tbody>
        </table>
	</div>
</div>

Bilet9/Areas/Admin/Views/Chef/Update.cshtml
@using Bilet9.Models
@model ChefUpdateVM
<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Enter Name">
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" class="form-control" placeholder="Enter Image">
        <span asp-validation-for="Image"></span>
    </div>
    <div class="form-check">
        <select asp-for="PositionId" class="form-control">
            @foreach (Position position in ViewBag.Positions)
            {
                <option value="@position.Id">@position.Title</option>
            }
        </select>
        <span asp-validation-for="PositionId"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>